[package]
name = "snowflake"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.7.2"

[dev-dependencies.tokio]
version = "1.6.1"
features = ["macros", "rt"]
